version: '3'

# 网桥mongo -> 方便相互通讯
networks:
  mongo:

services:
  # mongodb
  mongodb:
    image: mongo:4.4.6  # 原镜像`mongo:4.4.6`
    restart: unless-stopped
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /data/logs
    volumes:
      - D:\code-from-git-hub-in-sylvanas\docker-dev\mongo\db:/data/db
      - D:\code-from-git-hub-in-sylvanas\docker-dev\mongo\logs:/data/logs
    ports:
      - "27017:27017"
    networks:
      - mongo